-- ===============================================================
-- File: create_tables.sql
-- Project: Hospital Appointment & Billing Management System
-- Description: This script creates all main tables for the system
-- Created by: Faraz & Ashhal
-- ===============================================================

-- First, we’ll drop existing tables to avoid duplication errors during testing
DROP TABLE Prescription CASCADE CONSTRAINTS;
DROP TABLE Bill CASCADE CONSTRAINTS;
DROP TABLE Appointment CASCADE CONSTRAINTS;
DROP TABLE Doctor CASCADE CONSTRAINTS;
DROP TABLE Patient CASCADE CONSTRAINTS;
DROP TABLE Department CASCADE CONSTRAINTS;

-- ===============================================================
-- 1. DEPARTMENT TABLE
-- ===============================================================
-- Purpose: Stores all hospital departments like Cardiology, ENT, etc.
CREATE TABLE Department (
    dept_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_name VARCHAR2(50) NOT NULL,
    location VARCHAR2(50)
);

-- ===============================================================
-- 2. DOCTOR TABLE
-- ===============================================================
-- Purpose: Contains information about doctors, linked to a department.
CREATE TABLE Doctor (
    doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_name VARCHAR2(50) NOT NULL,
    specialization VARCHAR2(50),
    phone_no VARCHAR2(15),
    email VARCHAR2(50),
    dept_id NUMBER,
    consultation_fee NUMBER(8,2),
    CONSTRAINT fk_doctor_dept FOREIGN KEY (dept_id)
        REFERENCES Department(dept_id)
        ON DELETE SET NULL
);

-- ===============================================================
-- 3. PATIENT TABLE
-- ===============================================================
-- Purpose: Contains patient information like name, contact, and age.
CREATE TABLE Patient (
    patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_name VARCHAR2(50) NOT NULL,
    gender VARCHAR2(10),
    age NUMBER(3),
    phone_no VARCHAR2(15),
    email VARCHAR2(50),
    address VARCHAR2(100)
);

-- ===============================================================
-- 4. APPOINTMENT TABLE
-- ===============================================================
-- Purpose: Stores appointment details for patients and doctors.
-- Connected with both Doctor and Patient tables.
CREATE TABLE Appointment (
    appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_date DATE NOT NULL,
    appointment_time VARCHAR2(10),
    status VARCHAR2(20) DEFAULT 'Pending',
    doctor_id NUMBER NOT NULL,
    patient_id NUMBER NOT NULL,
    remarks VARCHAR2(100),
    CONSTRAINT fk_appointment_doctor FOREIGN KEY (doctor_id)
        REFERENCES Doctor(doctor_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id)
        REFERENCES Patient(patient_id)
        ON DELETE CASCADE
);

-- ===============================================================
-- 5. BILL TABLE
-- ===============================================================
-- Purpose: Manages billing information linked to appointments.
CREATE TABLE Bill (
    bill_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id NUMBER NOT NULL,
    total_amount NUMBER(10,2),
    payment_status VARCHAR2(20) DEFAULT 'Unpaid',
    payment_date DATE,
    CONSTRAINT fk_bill_appointment FOREIGN KEY (appointment_id)
        REFERENCES Appointment(appointment_id)
        ON DELETE CASCADE
);

-- ===============================================================
-- 6. PRESCRIPTION TABLE
-- ===============================================================
-- Purpose: Contains prescription details created after appointments.
CREATE TABLE Prescription (
    prescription_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id NUMBER NOT NULL,
    doctor_id NUMBER NOT NULL,
    patient_id NUMBER NOT NULL,
    prescription_date DATE DEFAULT SYSDATE,
    medicines VARCHAR2(200),
    remarks VARCHAR2(200),
    CONSTRAINT fk_presc_appointment FOREIGN KEY (appointment_id)
        REFERENCES Appointment(appointment_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_presc_doctor FOREIGN KEY (doctor_id)
        REFERENCES Doctor(doctor_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_presc_patient FOREIGN KEY (patient_id)
        REFERENCES Patient(patient_id)
        ON DELETE CASCADE
);

-- ===============================================================
-- END OF FILE
-- ===============================================================
-- All tables successfully created with PKs, FKs, and constraints.
-- Next step: Insert sample data using insert_sample_data.sql
