-- ===============================================================
-- File: test_queries.sql
-- Project: Hospital Appointment & Billing Management System
-- Description: Validation & testing queries for all features, triggers & views
-- Created by: Faraz & Ashhal
-- ===============================================================

-- NOTE:
-- This file demonstrates the working of the entire database.
-- You can take screenshots from these queries for your final report.
-- ===============================================================


-- ===============================================================
-- 1️⃣ BASIC DATA VERIFICATION
-- ===============================================================

-- 1.1 View all departments
SELECT * FROM Department;

-- 1.2 View all doctors with department info
SELECT d.doctor_id, d.doctor_name, d.specialization, dept.dept_name, d.consultation_fee
FROM Doctor d
JOIN Department dept ON d.dept_id = dept.dept_id;

-- 1.3 View all patients
SELECT * FROM Patient;

-- 1.4 View all appointments
SELECT appointment_id, appointment_date, appointment_time, status, doctor_id, patient_id, remarks
FROM Appointment;

-- 1.5 View all bills
SELECT * FROM Bill;

-- 1.6 View all prescriptions
SELECT * FROM Prescription;


-- ===============================================================
-- 2️⃣ TESTING TRIGGERS
-- ===============================================================

-- 2.1 Test Trigger: set_default_appointment_status
-- Try inserting an appointment without specifying 'status'
-- Expected: It should automatically set status to 'Pending'.
INSERT INTO Appointment (appointment_date, appointment_time, doctor_id, patient_id, remarks)
VALUES (TO_DATE('2025-10-25', 'YYYY-MM-DD'), '10:00 AM', 1, 2, 'Checkup - no status given');
SELECT appointment_id, status FROM Appointment WHERE appointment_date = TO_DATE('2025-10-25', 'YYYY-MM-DD');

-- 2.2 Test Trigger: prevent_double_booking
-- Try booking the same doctor for the same time and date
-- Expected: Error message "Doctor already has an appointment at this time."
-- (Uncomment the below line to test)
-- INSERT INTO Appointment (appointment_date, appointment_time, doctor_id, patient_id, remarks)
-- VALUES (TO_DATE('2025-10-22', 'YYYY-MM-DD'), '10:00 AM', 1, 3, 'Test double booking');

-- 2.3 Test Trigger: auto_generate_bill & auto_create_prescription
-- Update an appointment from 'Pending' to 'Completed'
-- Expected: Bill and Prescription records should be created automatically.
UPDATE Appointment
SET status = 'Completed'
WHERE appointment_id = 2;

-- Now check Bill and Prescription tables to confirm entries were added
SELECT * FROM Bill WHERE appointment_id = 2;
SELECT * FROM Prescription WHERE appointment_id = 2;

-- 2.4 Test Trigger: update_bill_status
-- Update a bill’s payment status to 'Paid'
-- Expected: Appointment’s status should change to 'Payment Received'
UPDATE Bill
SET payment_status = 'Paid', payment_date = SYSDATE
WHERE appointment_id = 2;

-- Verify the updated appointment status
SELECT appointment_id, status FROM Appointment WHERE appointment_id = 2;

-- 2.5 Test Trigger: appointment_audit_log (bonus)
-- View the log of appointment changes
SELECT * FROM Appointment_Log ORDER BY change_date DESC;


-- ===============================================================
-- 3️⃣ TESTING VIEWS
-- ===============================================================

-- 3.1 Daily Appointments View
SELECT * FROM daily_appointments_view;

-- 3.2 Pending Bills View
SELECT * FROM pending_bills_view;

-- 3.3 Doctor Summary View
SELECT * FROM doctor_summary_view;

-- 3.4 Patient History View
SELECT * FROM patient_history_view WHERE patient_name = 'Ali Raza';

-- 3.5 Department Doctors View
SELECT * FROM department_doctors_view;

-- 3.6 Prescription Summary View (bonus)
SELECT * FROM prescription_summary_view;


-- ===============================================================
-- 4️⃣ ADVANCED / AGGREGATION QUERIES
-- ===============================================================

-- 4.1 Find the total number of appointments in the system
SELECT COUNT(*) AS total_appointments FROM Appointment;

-- 4.2 Find total revenue generated by all doctors combined
SELECT SUM(total_amount) AS total_revenue FROM Bill WHERE payment_status = 'Paid';

-- 4.3 Show all doctors earning more than 2500 per appointment on average
SELECT doctor_name, consultation_fee
FROM Doctor
WHERE consultation_fee > 2500;

-- 4.4 Find patients who have more than 1 appointment
SELECT p.patient_name, COUNT(a.appointment_id) AS total_appointments
FROM Patient p
JOIN Appointment a ON p.patient_id = a.patient_id
GROUP BY p.patient_name
HAVING COUNT(a.appointment_id) > 1;

-- 4.5 Find total unpaid bills and number of pending appointments
SELECT 
    (SELECT COUNT(*) FROM Bill WHERE payment_status = 'Unpaid') AS unpaid_bills,
    (SELECT COUNT(*) FROM Appointment WHERE status = 'Pending') AS pending_appointments
FROM dual;


-- ===============================================================
-- 5️⃣ SECURITY / USER VALIDATION QUERIES (OPTIONAL)
-- ===============================================================

-- 5.1 Show currently connected Oracle user
SELECT USER FROM dual;

-- 5.2 Check all tables created by your schema
SELECT table_name FROM user_tables ORDER BY table_name;

-- 5.3 Show all triggers created
SELECT trigger_name FROM user_triggers ORDER BY trigger_name;

-- 5.4 Show all views created
SELECT view_name FROM user_views ORDER BY view_name;


-- ===============================================================
-- 6️⃣ CLEANUP TESTS (OPTIONAL)
-- ===============================================================

-- 6.1 Delete a test appointment (used for testing default trigger)
-- DELETE FROM Appointment WHERE appointment_date = TO_DATE('2025-10-25', 'YYYY-MM-DD');

-- 6.2 Rollback changes if needed (only during testing)
-- ROLLBACK;


-- ===============================================================
-- END OF FILE
-- ===============================================================
-- ✅ This file demonstrates that all features, triggers, and views work.
-- Take screenshots from each query result for your report.
-- You can now move on to Node.js backend (API layer) integration.
